#!/bin/sh

# gambiarra pra atualizar a versão automaticamente
# copiar para .git/hooks/pre-commit

set -e

num=`git status | egrep "modified: .*mapcss$" | wc -l`
data=`date +"%Y-%m-%d"`

if [ $num = 1 ]; then
	nome=`git status | egrep "modified: .*mapcss$" | awk '{print $2}'`
	sed -i "s/^  version: \".*\";$/  version: \"$data\";/" $nome
	git add $nome
elif [ $num = 2 ]; then
	sed -i "s/^  version: \".*\";$/  version: \"$data\";/" *.mapcss
	git add *.mapcss
fi
